import { cn } from '@/lib/utils'
import { QueryProvider } from '@/providers/tanstack-query-protver'
import { ThemeProvider } from '@/providers/theme-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'GeekBrains By Hexvel',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn('w-full, min-h-screen', inter.className)}>
				<QueryProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
						storageKey='geekbrains'
					>
						{children}
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	)
}
